
package postegre.mediatheque.interfacecxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.0
 * Wed Jan 31 12:41:57 CET 2018
 * Generated source version: 3.2.0
 */

@XmlRootElement(name = "add", namespace = "http://interfacecxf.mediatheque.postegre/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "add", namespace = "http://interfacecxf.mediatheque.postegre/")

public class Add {

    @XmlElement(name = "arg0")
    private postgre.mediatheque.entite.Membre arg0;

    public postgre.mediatheque.entite.Membre getArg0() {
        return this.arg0;
    }

    public void setArg0(postgre.mediatheque.entite.Membre newArg0)  {
        this.arg0 = newArg0;
    }

}

