
package postegre.mediatheque.interfacecxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.0
 * Wed Jan 31 12:41:56 CET 2018
 * Generated source version: 3.2.0
 */

@XmlRootElement(name = "existMembreResponse", namespace = "http://interfacecxf.mediatheque.postegre/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "existMembreResponse", namespace = "http://interfacecxf.mediatheque.postegre/")

public class ExistMembreResponse {

    @XmlElement(name = "return")
    private boolean _return;

    public boolean getReturn() {
        return this._return;
    }

    public void setReturn(boolean new_return)  {
        this._return = new_return;
    }

}

