
package postegre.mediatheque.interfacecxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.0
 * Wed Jan 31 12:41:57 CET 2018
 * Generated source version: 3.2.0
 */

@XmlRootElement(name = "getMembreAllResponse", namespace = "http://interfacecxf.mediatheque.postegre/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMembreAllResponse", namespace = "http://interfacecxf.mediatheque.postegre/")

public class GetMembreAllResponse {

    @XmlElement(name = "return")
    private java.util.List _return;

    public java.util.List getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List new_return)  {
        this._return = new_return;
    }

}

