
package postegre.mediatheque.interfacecxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.0
 * Wed Jan 31 14:58:39 CET 2018
 * Generated source version: 3.2.0
 */

@XmlRootElement(name = "MediathequeException", namespace = "http://util.mediatheque.postgre/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MediathequeException", namespace = "http://util.mediatheque.postgre/")

public class MediathequeExceptionBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

